using WorkAudit.Domain;
using WorkAudit.Storage;
using System.Globalization;

namespace WorkAudit.Core.Reports;

/// <summary>
/// Provides localized strings for reports. Supports English and Arabic.
/// </summary>
public static class ReportLocalizationService
{
    private const string LangKey = "report_language";
    // Contract: report_language controls localized text only; app shell layout remains LTR.
    public static readonly System.Windows.FlowDirection ShellFlowDirection = System.Windows.FlowDirection.LeftToRight;

    private static readonly Dictionary<string, (string En, string Ar)> Strings = new()
    {
        ["ExecutiveSummary"] = ("Executive Summary Report", "تقرير الملخص التنفيذي"),
        ["KeyMetrics"] = ("Key Metrics", "المؤشرات الرئيسية"),
        ["TotalDocuments"] = ("Total Documents", "إجمالي المستندات"),
        ["Throughput"] = ("Throughput", "الإنتاجية"),
        ["ClearingRate"] = ("Clearing Rate", "معدل التصفية"),
        ["IssueRate"] = ("Issue Rate", "معدل المشكلات"),
        ["ByBranch"] = ("By Branch (Top 5)", "حسب الفرع (أعلى 5)"),
        ["BySection"] = ("By Section (Top 5)", "حسب القسم (أعلى 5)"),
        ["Issues"] = ("Issues", "المشكلات"),
        ["FixedThisPeriod"] = ("Fixed this period", "تم إصلاحها هذه الفترة"),
        ["StillOutstanding"] = ("Still outstanding", "ما زالت قائمة"),
        ["TopBranchesWithIssues"] = ("Top branches with issues", "أعلى الفروع بالمشكلات"),
        ["DocumentsByBranch"] = ("Documents by Branch", "المستندات حسب الفرع"),
        ["Documents"] = ("documents", "مستندات"),
        // Assignment UI
        ["AssignDocuments"] = ("Assign Documents", "تعيين المستندات"),
        ["SelectedDocuments"] = ("Selected documents", "المستندات المحددة"),
        ["AssignTo"] = ("Assign to:", "تعيين إلى:"),
        ["DueDateOptional"] = ("Due date (optional):", "تاريخ الاستحقاق (اختياري):"),
        ["Priority"] = ("Priority:", "الأولوية:"),
        ["Notes"] = ("Notes:", "ملاحظات:"),
        ["Assign"] = ("Assign", "تعيين"),
        ["Cancel"] = ("Cancel", "إلغاء"),
        ["Filter"] = ("Filter", "تصفية"),
        ["ShowOverdueOnly"] = ("Show overdue only", "عرض المتأخرة فقط"),
        ["StartReview"] = ("Start Review", "بدء المراجعة"),
        ["MarkComplete"] = ("Mark Complete", "تحديد كمكتمل"),
        ["ViewDocument"] = ("View Document", "عرض المستند"),
        ["CancelAssignment"] = ("Cancel Assignment", "إلغاء المهمة"),
        ["CompletionNote"] = ("Completion note (required):", "ملاحظة الإكمال (مطلوبة):"),
        ["CompletionType"] = ("Type:", "النوع:"),
        ["CompletionSeverity"] = ("Severity:", "الأولوية:"),
        ["CompletionNoteRequired"] = ("Please enter a completion note.", "يرجى إدخال ملاحظة الإكمال."),
        ["AssignmentCompleted"] = ("Assignment completed.", "تم إكمال المهمة."),
        ["AssignedBy"] = ("Assigned By", "تم التعيين بواسطة"),
        ["Pending"] = ("Pending", "قيد الانتظار"),
        ["InProgress"] = ("In Progress", "قيد التنفيذ"),
        ["Completed"] = ("Completed", "مكتمل"),
        ["Cancelled"] = ("Cancelled", "ملغى"),
        ["Overdue"] = ("Overdue", "متأخر"),
        ["Low"] = ("Low", "منخفضة"),
        ["Normal"] = ("Normal", "عادية"),
        ["Urgent"] = ("Urgent", "عاجلة"),
        ["DueToday"] = ("Due today", "مستحق اليوم"),
        ["DueTomorrow"] = ("Due tomorrow", "مستحق غداً"),
        ["DueInDays"] = ("Due in {0} days", "مستحق خلال {0} يوم"),
        ["OverdueByDays"] = ("Overdue by {0} day(s)", "متأخر بـ {0} يوم"),
        // MainWindow - Menus
        ["AppTitle"] = ("AUDITA v1 – Audit Workspace", "AUDITA v1 – مساحة عمل تدقيق"),
        ["AppBrandName"] = ("AUDITA", "AUDITA"),
        ["AuditaProductTitle"] = ("AUDITA v1", "AUDITA v1"),
        ["AuditaSignInWindowTitle"] = ("AUDITA – Sign In", "AUDITA – تسجيل الدخول"),
        ["File"] = ("File", "ملف"),
        ["OpenFiles"] = ("Open File(s)...", "فتح ملف(ات)..."),
        ["OpenFolder"] = ("Open Folder...", "فتح مجلد..."),
        ["RecentFiles"] = ("Recent Files", "الملفات الأخيرة"),
        ["SaveProject"] = ("Save Project", "حفظ المشروع"),
        ["LoadProject"] = ("Load Project", "تحميل المشروع"),
        ["Export"] = ("Export", "تصدير"),
        ["ExportPdf"] = ("Export as PDF", "تصدير كـ PDF"),
        ["ExportZip"] = ("Export as ZIP", "تصدير كـ ZIP"),
        ["SignOut"] = ("Sign Out", "تسجيل الخروج"),
        ["Exit"] = ("Exit", "خروج"),
        ["Undo"] = ("Undo", "تراجع"),
        ["Redo"] = ("Redo", "إعادة"),
        ["ClearPreview"] = ("Clear Preview", "مسح المعاينة"),
        ["Preferences"] = ("Preferences", "التفضيلات"),
        ["View"] = ("View", "عرض"),
        ["Properties"] = ("Properties", "الخصائص"),
        ["GoTo"] = ("Go to", "انتقل إلى"),
        ["Input"] = ("Input", "إدخال"),
        ["Processing"] = ("Processing", "معالجة"),
        ["Workspace"] = ("Workspace", "مساحة العمل"),
        ["Archive"] = ("Archive", "أرشيف"),
        ["DocumentPreview"] = ("Document Preview", "معاينة المستند"),
        ["Tools"] = ("Tools", "أدوات"),
        ["Dashboard"] = ("Dashboard", "لوحة المعلومات"),
        ["AuditorDashboard"] = ("Auditor Dashboard", "لوحة معلومات المدقق"),
        ["MyPerformance"] = ("My Performance", "أدائي"),
        ["MyAssignments"] = ("My Assignments", "مهامي"),
        ["BranchOverview"] = ("Branch Overview", "نظرة عامة على الفرع"),
        ["DailyJournal"] = ("Daily Journal", "المذكرة اليومية"),
        ["MyRecentActivity"] = ("My Recent Activity", "نشاطي الأخير"),
        ["QuickActions"] = ("Quick Actions", "إجراءات سريعة"),
        ["FollowUps"] = ("Follow-ups", "متابعات"),
        ["BranchPerformance"] = ("Branch Performance", "أداء الفرع"),
        ["Reports"] = ("Reports", "تقارير"),
        ["MyReports"] = ("My Reports", "تقاريري"),
        ["AuditorReportsSubtitle"] = ("Generate auditor reports for your branch and assignments", "إنشاء تقارير المدقق لفرعك ومهامك"),
        ["ChatWithAI"] = ("Chat with AI", "محادثة مع الذكاء الاصطناعي"),
        ["ToggleSidebar"] = ("Toggle Sidebar", "إظهار/إخفاء الشريط الجانبي"),
        ["ControlPanel"] = ("Control Panel...", "لوحة التحكم..."),
        ["ToolsView"] = ("Tools View", "عرض الأدوات"),
        ["BatchProcess"] = ("Batch Process", "معالجة دفعة"),
        ["Admin"] = ("Admin", "إدارة"),
        ["UserManagement"] = ("User Management", "إدارة المستخدمين"),
        ["AssignmentManagement"] = ("Assignment Management", "إدارة المهام"),
        ["TeamTaskManagement"] = ("Team Tasks...", "مهام الفريق..."),
        ["TeamTaskManagementTitle"] = ("Team task management", "إدارة مهام الفريق"),
        ["TeamTaskManagementSubtitle"] = ("Assign recurring checklist tasks to users (daily, weekly, or monthly).", "تعيين مهام قوائم متكررة للمستخدمين (يومية أو أسبوعية أو شهرية)."),
        ["TeamTaskFilterAssignee"] = ("Assignee:", "المكلف:"),
        ["TeamTaskColTitle"] = ("Title", "العنوان"),
        ["TeamTaskColAssignee"] = ("Assignee", "المكلف"),
        ["TeamTaskColRecurrence"] = ("Recurrence", "التكرار"),
        ["TeamTaskColStart"] = ("Start", "البداية"),
        ["TeamTaskColEnd"] = ("End", "النهاية"),
        ["TeamTaskColActive"] = ("Active", "نشط"),
        ["MyTeamTasksTitle"] = ("My team tasks", "مهام فريقي"),
        ["MyTeamTasksSubtitle"] = ("Tick when done for the current period.", "حدد عند الإنجاز للفترة الحالية."),
        ["MyTeamTasksSubtitleWithNote"] = ("Tick when done. Click the task text to add a note for this period.", "حدد عند الإنجاز. انقر نص المهمة لإضافة ملاحظة لهذه الفترة."),
        ["MyTeamTasksEmpty"] = ("No team tasks for this period.", "لا توجد مهام فريق لهذه الفترة."),
        ["TeamTaskClickForNote"] = ("Click to add or edit a note for this period", "انقر لإضافة أو تحرير ملاحظة لهذه الفترة"),
        ["TeamTaskNoteInlineBadge"] = ("Note", "ملاحظة"),
        ["TeamTaskNoteDialogTitle"] = ("Team task note", "ملاحظة مهمة الفريق"),
        ["TeamTaskNoteHint"] = ("Your note is saved for the current day, week, or month (depending on the task). Clear the text and click OK to remove the note.", "تُحفظ ملاحظتك لليوم أو الأسبوع أو الشهر الحالي (حسب المهمة). امسح النص واضغط موافق لإزالة الملاحظة."),
        ["TeamTaskNoteSaveFailed"] = ("Could not save the note.", "تعذر حفظ الملاحظة."),
        ["AuditLog"] = ("Audit Log", "سجل التدقيق"),
        ["Help"] = ("Help", "مساعدة"),
        ["Documentation"] = ("Documentation", "التوثيق"),
        ["KeyboardShortcuts"] = ("Keyboard Shortcuts", "اختصارات لوحة المفاتيح"),
        ["ShortcutsTab"] = ("Shortcuts", "اختصارات"),
        ["ShortcutsIntro"] = ("Click Set, then press the new key combination. Press Esc to cancel capture. Changes apply when you click Save All Settings.", "انقر «تعيين» ثم اضغط الاختصار الجديد. اضغط Esc لإلغاء الالتقاط. تُطبق التغييرات عند حفظ جميع الإعدادات."),
        ["ShortcutsSet"] = ("Set…", "تعيين…"),
        ["ShortcutsResetAll"] = ("Reset all to defaults", "استعادة الافتراضي للجميع"),
        ["ShortcutCapturePress"] = ("Press keys… (Esc to cancel)", "اضغط المفاتيح… (Esc للإلغاء)"),
        ["ShortcutAction_ProcessingMerge"] = ("Processing: Merge to PDF", "المعالجة: دمج في PDF"),
        ["ShortcutAction_ProcessingMergeAlternate"] = ("Processing: Merge to PDF (alternate)", "المعالجة: دمج في PDF (بديل)"),
        ["ShortcutAction_ProcessingRefresh"] = ("Processing: Refresh list", "المعالجة: تحديث القائمة"),
        ["ShortcutAction_ProcessingSelectAllChecks"] = ("Processing: Check all rows", "المعالجة: تحديد كل الصفوف"),
        ["ShortcutAction_ProcessingClearChecks"] = ("Processing: Clear all checkboxes", "المعالجة: مسح كل مربعات التحديد"),
        ["ShortcutAction_ProcessingUncheckRow"] = ("Processing: Uncheck selected row", "المعالجة: إلغاء تحديد الصف"),
        ["ShortcutAction_ProcessingGridSelectAll"] = ("Processing grid: Select all (same as check all)", "شبكة المعالجة: تحديد الكل"),
        ["ShortcutAction_ProcessingSetTypeSection"] = ("Processing: Set type/section", "المعالجة: تعيين النوع/القسم"),
        ["ShortcutAction_ProcessingDeleteSelected"] = ("Processing: Delete selected documents", "المعالجة: حذف المستندات المحددة"),
        ["About"] = ("About", "حول"),
        ["More"] = ("More", "المزيد"),
        ["Ready"] = ("Ready", "جاهز"),
        ["TooltipDashboard"] = ("Admin/Manager Dashboard", "لوحة معلومات المدير/المشرف"),
        ["TooltipImport"] = ("Import files or capture via webcam", "استيراد ملفات أو التقاط عبر الكاميرا"),
        ["TooltipProcessing"] = ("Document processing pipeline", "خط معالجة المستندات"),
        ["TooltipWorkspace"] = ("Review documents, add notes", "مراجعة المستندات وإضافة ملاحظات"),
        ["TooltipArchive"] = ("Search and export", "البحث والتصدير"),
        ["TooltipTools"] = ("Backup, Control (View → Tools)", "النسخ الاحتياطي، التحكم"),
        ["TooltipReports"] = ("Reports (View → Reports)", "التقارير"),
        ["TooltipSidebar"] = ("Toggle panel on/off (Ctrl+B)", "إظهار/إخفاء اللوحة"),
        ["SignedInAs"] = ("Signed in as {0}", "تم تسجيل الدخول كـ {0}"),
        // Control Panel
        ["ControlPanelTitle"] = ("Control Panel", "لوحة التحكم"),
        ["ControlPanelSubtitle"] = ("Configure document types, branches, security, and system settings", "تكوين أنواع المستندات والفروع والأمان وإعدادات النظام"),
        ["PreferencesWindowTitle"] = ("Preferences", "التفضيلات"),
        ["PreferencesWindowSubtitle"] = ("Language, appearance, keyboard shortcuts, and on-device OCR.", "اللغة والمظهر واختصارات لوحة المفاتيح والتعرف الضوئي على الجهاز."),
        ["SavePreferences"] = ("Save Settings", "حفظ الإعدادات"),
        ["ShortcutsIntroPreferences"] = ("Click Set, then press the new key combination. Press Esc to cancel capture. Changes apply when you click Save Settings.", "انقر «تعيين» ثم اضغط الاختصار الجديد. اضغط Esc لإلغاء الالتقاط. تُطبق التغييرات عند النقر على حفظ الإعدادات."),
        ["OcrTab"] = ("OCR", "التعرف الضوئي"),
        ["OcrTabIntro"] = ("On-device text extraction from scans and images using Tesseract and local tessdata files.", "استخراج النصوص على الجهاز من الممسوحات والصور باستخدام Tesseract وملفات tessdata المحلية."),
        ["General"] = ("General", "عام"),
        ["ApplicationLanguage"] = ("Application Language", "لغة التطبيق"),
        ["DocumentTypes"] = ("Document Types", "أنواع المستندات"),
        ["Branches"] = ("Branches", "الفروع"),
        ["Security"] = ("Security", "الأمان"),
        ["Workflow"] = ("Workflow", "سير العمل"),
        ["Backup"] = ("Backup", "النسخ الاحتياطي"),
        ["System"] = ("System", "النظام"),
        ["AddNew"] = ("Add New", "إضافة جديد"),
        ["Edit"] = ("Edit", "تحرير"),
        ["Delete"] = ("Delete", "حذف"),
        ["SaveAllSettings"] = ("Save All Settings", "حفظ جميع الإعدادات"),
        ["Close"] = ("Close", "إغلاق"),
        ["Language"] = ("Language:", "اللغة:"),
        ["AppLanguageDescription"] = ("Language for the entire application (menus, views, reports). English or Arabic.", "لغة التطبيق بالكامل (القوائم والعروض والتقارير). الإنجليزية أو العربية."),
        ["Appearance"] = ("Appearance", "المظهر"),
        ["Theme"] = ("Theme:", "المظهر:"),
        ["ShowInactive"] = ("Show inactive", "عرض غير النشطة"),
        // Login / Identity
        ["SignIn"] = ("Sign In", "تسجيل الدخول"),
        ["Username"] = ("Username", "اسم المستخدم"),
        ["Password"] = ("Password", "كلمة المرور"),
        ["ShowPassword"] = ("Show password", "إظهار كلمة المرور"),
        ["HidePassword"] = ("Hide password", "إخفاء كلمة المرور"),
        ["DocumentScannerForBankAuditors"] = ("Audit Workspace for Documents, Notes & Reporting", "مساحة عمل تدقيق للمستندات والملاحظات والتقارير"),
        ["IdentityPrompt"] = ("Enter your name or staff ID to start the session:", "أدخل اسمك أو رقم الموظف لبدء الجلسة:"),
        ["Identity"] = ("Identity", "الهوية"),
        ["OK"] = ("OK", "موافق"),
        ["Import"] = ("Import", "استيراد"),
        ["Webcam"] = ("Webcam", "الكاميرا"),
        // ProcessingView
        ["NoDocuments"] = ("No documents", "لا توجد مستندات"),
        ["Shown"] = ("Shown: {0}", "المعروض: {0}"),
        ["ShownLabel"] = ("Shown", "المعروض"),
        ["DocumentsCount"] = ("{0} documents", "{0} مستندات"),
        ["FilterByType"] = ("Filter by type", "تصفية حسب النوع"),
        ["ClearFilter"] = ("Clear filter", "مسح الفلتر"),
        ["ProcessingQueueScope"] = ("Queue scope", "نطاق القائمة"),
        ["ProcessingQueueScopeAll"] = ("All", "الكل"),
        ["ProcessingQueueScopeMyWork"] = ("My work", "عملي"),
        ["ProcessingQueueScopePerUser"] = ("Per user", "لمستخدم"),
        ["ProcessingQueueScopeUser"] = ("User", "المستخدم"),
        ["MoveToWorkspace"] = ("Move to Workspace", "نقل إلى مساحة العمل"),
        ["DocumentsMovedToWorkspace"] = ("{0} document(s) moved to Workspace.", "{0} مستند(ات) تم نقلها إلى مساحة العمل."),
        ["DocumentsArchived"] = ("{0} document(s) archived.", "{0} مستند(ات) تمت أرشفتها."),
        ["MoveToArchive"] = ("Move to Archive", "نقل إلى الأرشيف"),
        ["MoveToArchiveTooltip"] = ("Send selected documents to Archive (retention and immutability apply). Requires archive:create.", "إرسال المستندات المحددة إلى الأرشيف."),
        ["MoveToArchiveConfirm"] = ("Move {0} document(s) to Archive? They will leave the Workspace list.", "نقل {0} مستند(ات) إلى الأرشيف؟ ستُزال من مساحة العمل."),
        ["MoveToArchiveNoPermission"] = ("You do not have permission to archive documents.", "ليس لديك إذن لأرشفة المستندات."),
        ["SelectDocumentsFirst"] = ("Please select one or more documents first.", "يرجى تحديد مستند واحد أو أكثر أولاً."),
        ["Refresh"] = ("Refresh", "تحديث"),
        ["ProcessingRefreshTooltip"] = ("Reload the Processing queue from the database. Shortcut: {0}.", "إعادة تحميل قائمة المعالجة من قاعدة البيانات. اختصار: {0}."),
        ["SetTypeSection"] = ("Set type/section...", "تعيين النوع/القسم..."),
        ["MergeToPdf"] = ("Merge to PDF…", "دمج في PDF…"),
        ["MergeToPdfTooltip"] = ("Combine selected PDFs and images into one document in this list", "دمج ملفات PDF والصور المحددة في مستند واحد في هذه القائمة"),
        ["MergeToPdfProgress"] = ("Merging to PDF...", "جاري الدمج في PDF..."),
        ["MergeToPdfTitle"] = ("Merge to PDF", "دمج في PDF"),
        ["MergeToPdfNeedTwo"] = ("Select at least two PDF or image documents with accessible files.", "حدد مستندي PDF أو صورتين على الأقل بملفات متاحة."),
        ["MergeToPdfLockedExcluded"] = ("{0} document(s) excluded (not accessible).", "تم استبعاد {0} مستند(ات) (غير متاح)."),
        ["MergeToPdfMerged"] = ("The merged PDF was added to the Processing queue.", "تمت إضافة PDF المدمج إلى قائمة المعالجة."),
        ["MergeToPdfCannotDeleteSources"] = ("You do not have permission to remove the original documents after merge. Merge was cancelled.", "ليس لديك إذن لإزالة المستندات الأصلية بعد الدمج. تم إلغاء الدمج."),
        ["MergeToPdfImportFailed"] = ("The merged file could not be added. It may be a duplicate of an existing document, or saving failed.", "تعذرت إضافة الملف المدمج. قد يكون مكرراً أو فشل الحفظ."),
        ["MergeToPdfFailed"] = ("Merge failed:\n{0}", "فشل الدمج:\n{0}"),
        ["MergeToPdfSkippedOther"] = ("{0} selected item(s) skipped (not a PDF/image or file missing).", "تم تخطي {0} عنصر(ات) (ليس PDF/صورة أو الملف مفقود)."),
        ["MergeToPdfTooltipExtended"] = ("Combine selected PDFs and images into one document in this list. Shortcuts: {0} or {1}. Shift+click rows to check a range.", "دمج ملفات PDF والصور المحددة في مستند واحد في هذه القائمة. اختصار: {0} أو {1}. Shift+نقر لتحديد نطاق من الصفوف."),
        ["MergeToPdfLossyRasterTitle"] = ("Merge quality", "جودة الدمج"),
        ["MergeToPdfLossyRasterPrompt"] = ("The following PDF file(s) cannot be merged without re-rendering (image quality may be lower than the original):\n\n{0}\n\nContinue with reduced quality for those files?", "لا يمكن دمج ملفات PDF التالية بدون إعادة رسم الصفحات (قد تقل الجودة عن الأصل):\n\n{0}\n\nهل تريد المتابعة بجودة أقل لهذه الملفات؟"),
        ["MergeToPdfLossyRasterMoreFiles"] = ("... and {0} more.", "... و{0} أخرى."),
        ["DeleteSelected"] = ("Delete selected", "حذف المحدد"),
        ["DocumentsUpdated"] = ("{0} document(s) updated.", "تم تحديث {0} مستند(ات)."),
        ["UpdateFailed"] = ("Failed to update document(s).", "فشل تحديث المستند(ات)."),
        ["TypeLabel"] = ("Type:", "النوع:"),
        ["SectionLabel"] = ("Section:", "القسم:"),
        ["SuggestSimilar"] = ("Suggest Similar", "اقتراح مشابه"),
        ["ProcessOptions"] = ("Process options:", "خيارات المعالجة:"),
        ["SkipAlreadyClassified"] = ("Skip already classified", "تخطي المصنفة مسبقاً"),
        ["TextExtractionOnlyWhenNeeded"] = ("Text extraction only when needed", "استخراج النص عند الحاجة فقط"),
        ["IncludeLlmExplanation"] = ("Include LLM explanation", "تضمين شرح LLM"),
        ["ProcessSteps"] = ("Process steps:", "خطوات المعالجة:"),
        ["TextExtractionVision"] = ("Text extraction (Vision)", "استخراج النص (الرؤية)"),
        ["MlClassification"] = ("ML Classification", "تصنيف ML"),
        ["LlmAnalysis"] = ("LLM Analysis", "تحليل LLM"),
        ["EntityExtraction"] = ("Entity Extraction", "استخراج الكيانات"),
        ["ServiceStatus"] = ("Service Status:", "حالة الخدمة:"),
        ["VisionChecking"] = ("Vision: checking...", "الرؤية: جاري التحقق..."),
        ["LlmChecking"] = ("LLM: checking...", "LLM: جاري التحقق..."),
        ["Filters"] = ("Filters:", "الفلاتر:"),
        ["AllStatuses"] = ("All statuses", "جميع الحالات"),
        ["Draft"] = ("Draft", "مسودة"),
        ["Reviewed"] = ("Reviewed", "تمت المراجعة"),
        ["ReadyForAudit"] = ("Ready for Audit", "جاهز للتدقيق"),
        ["Cleared"] = ("Cleared", "تم التصفية"),
        ["AllConfidence"] = ("All confidence", "جميع الثقة"),
        ["NeedReview"] = ("Need review (<50%)", "يحتاج مراجعة (<50%)"),
        ["MediumConfidence"] = ("Medium (50-80%)", "متوسط (50-80%)"),
        ["HighConfidence"] = ("High (>80%)", "عالي (>80%)"),
        ["HideCleared"] = ("Hide cleared", "إخفاء المصفاة"),
        ["ClearFilters"] = ("Clear filters", "مسح الفلاتر"),
        ["RecentlyProcessedDocuments"] = ("Recently Processed Documents", "المستندات المعالجة مؤخراً"),
        ["SelectAll"] = ("Select All", "تحديد الكل"),
        ["SelectAllTooltip"] = ("Check all rows in the list for bulk actions. Shortcuts: {0} (sidebar) or {1} (grid).", "تحديد جميع الصفوف في القائمة للإجراءات الجماعية. اختصار: {0} (الشريط) أو {1} (الشبكة)."),
        ["ProcessingClearSelectionTooltip"] = ("Clear all checkboxes. Shortcut: {0}.", "مسح جميع مربعات التحديد. اختصار: {0}."),
        ["Clear"] = ("Clear", "مسح"),
        ["NoDocumentsLast7Days"] = ("No documents in the last 7 days. Use Input to import or capture documents.", "لا توجد مستندات في آخر 7 أيام. استخدم الإدخال لاستيراد أو التقاط المستندات."),
        ["HidePreview"] = ("Hide preview", "إخفاء المعاينة"),
        ["SelectDocumentToPreview"] = ("Select a document to preview.", "حدد مستنداً للمعاينة."),
        ["Summary"] = ("Summary: ", "الملخص: "),
        ["CompletedLast7Days"] = ("{0} completed (last 7 days)", "{0} مكتمل (آخر 7 أيام)"),
        ["DraftCount"] = ("Draft: {0}", "مسودة: {0}"),
        ["ReviewedCount"] = ("Reviewed: {0}", "تمت المراجعة: {0}"),
        ["NeedReviewCount"] = ("Need Review: {0}", "يحتاج مراجعة: {0}"),
        ["TotalCount"] = ("Total: {0}", "الإجمالي: {0}"),
        ["Finish"] = ("Finish", "إنهاء"),
        ["Name"] = ("Name", "الاسم"),
        ["Keywords"] = ("Keywords", "الكلمات المفتاحية"),
        ["Active"] = ("Active", "نشط"),
        ["Order"] = ("Order", "الترتيب"),
        ["Code"] = ("Code", "الكود"),
        ["Branch"] = ("Branch", "الفرع"),
        ["DocumentTypesCount"] = ("{0} document types", "{0} أنواع مستندات"),
        ["BranchesCount"] = ("{0} branches", "{0} فروع"),
        ["AllTypes"] = ("All types", "جميع الأنواع"),
        ["NoDocumentsLast7DaysLabel"] = ("No documents in last 7 days", "لا توجد مستندات في آخر 7 أيام"),
        ["ShowingRecentDocuments"] = ("Showing {0} recent documents", "عرض {0} مستندات حديثة"),
        ["ActiveFilters"] = ("Active: {0}", "نشط: {0}"),
        // ArchiveView
        ["Type"] = ("Type", "النوع"),
        ["LegalHold"] = ("Legal Hold", "الحجز القانوني"),
        ["CaptureDateFrom"] = ("Capture Date From", "تاريخ الالتقاط من"),
        ["CaptureDateTo"] = ("Capture Date To", "تاريخ الالتقاط إلى"),
        ["DocumentDateFrom"] = ("Document Date From", "تاريخ المستند من"),
        ["DocumentDateTo"] = ("Document Date To", "تاريخ المستند إلى"),
        ["ArchivedFrom"] = ("Archived From", "أرشفة من"),
        ["ArchivedTo"] = ("Archived To", "أرشفة إلى"),
        ["ExpiringWithin"] = ("Expiring Within", "تنتهي خلال"),
        ["Tag"] = ("Tag", "الوسم"),
        ["Custodian"] = ("Custodian", "الوصي"),
        ["Disposal"] = ("Disposal", "التخلص"),
        ["TextSearch"] = ("Text Search", "بحث النص"),
        ["Search"] = ("Search", "بحث"),
        ["ArchiveStats"] = ("Archive stats: ", "إحصائيات الأرشيف: "),
        ["SaveSearch"] = ("Save Search", "حفظ البحث"),
        ["Columns"] = ("Columns", "الأعمدة"),
        ["ApplyLegalHold"] = ("Apply Legal Hold", "تطبيق الحجز القانوني"),
        ["ReleaseLegalHold"] = ("Release Legal Hold", "إلغاء الحجز القانوني"),
        ["BulkTag"] = ("Bulk Tag", "وسم جماعي"),
        ["AssignCustodian"] = ("Assign Custodian", "تعيين الوصي"),
        ["RequestDisposal"] = ("Request Disposal", "طلب التخلص"),
        ["ApproveDisposal"] = ("Approve Disposal", "الموافقة على التخلص"),
        ["RejectDisposal"] = ("Reject Disposal", "رفض التخلص"),
        ["ExportArchive"] = ("Export", "تصدير"),
        ["Encrypt"] = ("Encrypt", "تشفير"),
        ["ChainOfCustody"] = ("Chain of Custody", "سلسلة الوصاية"),
        // ReportsView
        ["ReportConfiguration"] = ("Report Configuration", "تكوين التقرير"),
        ["Period"] = ("Period:", "الفترة:"),
        ["DateRange"] = ("Date Range:", "نطاق التاريخ:"),
        ["To"] = ("to", "إلى"),
        ["Format"] = ("Format:", "التنسيق:"),
        ["FiltersOptional"] = ("Filters (Optional)", "الفلاتر (اختياري)"),
        ["Status"] = ("Status:", "الحالة:"),
        ["DocType"] = ("Doc Type:", "نوع المستند:"),
        ["Engagement"] = ("Engagement:", "المشاركة:"),
        ["User"] = ("User:", "المستخدم:"),
        ["ReportType"] = ("Report Type", "نوع التقرير"),
        ["DailySummary"] = ("Daily Summary", "ملخص يومي"),
        ["BranchSummary"] = ("Branch Summary", "ملخص الفرع"),
        ["SectionSummary"] = ("Section Summary", "ملخص القسم"),
        ["StatusSummary"] = ("Status Summary", "ملخص الحالة"),
        ["DocumentTypeReport"] = ("Document Type", "نوع المستند"),
        ["Performance"] = ("Performance", "الأداء"),
        ["IssuesFocus"] = ("Issues & Focus", "المشكلات والتركيز"),
        ["UserActivity"] = ("User Activity", "نشاط المستخدم"),
        ["AssignmentSummary"] = ("Assignment Summary", "ملخص المهام"),
        ["AuditTrail"] = ("Audit Trail", "سجل التدقيق"),
        ["IncludeCharts"] = ("Include charts (where applicable)", "تضمين الرسوم البيانية (حيث ينطبق)"),
        ["ExportPerBranch"] = ("Export per branch/section (multiple PDFs)", "تصدير لكل فرع/قسم (PDF متعددة)"),
        ["ZipOutput"] = ("ZIP output", "إخراج ZIP"),
        ["Template"] = ("Template:", "القالب:"),
        ["Watermark"] = ("Watermark:", "العلامة المائية:"),
        ["GenerateReport"] = ("Generate Report", "إنشاء التقرير"),
        ["SaveConfiguration"] = ("Save Configuration", "حفظ التكوين"),
        ["LoadSaved"] = ("Load Saved...", "تحميل المحفوظ..."),
        // ToolsView
        ["TesseractLanguage"] = ("Tesseract language", "لغة Tesseract"),
        ["ExportBackupToExternal"] = ("Export backup to USB or network drive", "تصدير النسخ الاحتياطي إلى USB أو محرك الشبكة"),
        ["BackupToExternalDrive"] = ("Backup to external drive...", "النسخ الاحتياطي إلى محرك خارجي..."),
        ["DecryptEncryptedExport"] = ("Decrypt encrypted archive exports", "فك تشفير صادرات الأرشيف المشفرة"),
        ["DecryptExportFile"] = ("Decrypt export file...", "فك تشفير ملف التصدير..."),
        ["TrainingRetrainPipeline"] = ("Training, retrain, pipeline test, folders", "التدريب، إعادة التدريب، اختبار الأنبوب، المجلدات"),
        ["ExportClassificationFeedback"] = ("Export classification feedback (CSV)", "تصدير ملاحظات التصنيف (CSV)"),
        ["TrainModel"] = ("Train model", "تدريب النموذج"),
        ["RetrainFromCorrections"] = ("Retrain from corrections", "إعادة التدريب من التصحيحات"),
        ["PipelineTest"] = ("Pipeline test", "اختبار الأنبوب"),
        ["Control"] = ("Control", "التحكم"),

        // Intelligence Dashboard
        ["IntelligenceDashboard"] = ("Intelligence Dashboard", "لوحة المعلومات الذكية"),
        ["AutoGeneratedSummary"] = ("Auto-Generated Summary", "ملخص تلقائي"),
        ["SmartRecommendations"] = ("Smart Recommendations", "التوصيات الذكية"),
        ["NotesAndObservations"] = ("Notes & Observations", "الملاحظات والمشاهدات"),
        ["NoNotesRecorded"] = ("No notes recorded for this period", "لا توجد ملاحظات مسجلة لهذه الفترة"),
        ["TotalNotesRecorded"] = ("Total Notes Recorded", "إجمالي الملاحظات المسجلة"),
        ["ViewNotes"] = ("View Notes", "عرض الملاحظات"),
        ["NoteCount"] = ("Note Count", "عدد الملاحظات"),
        ["AddNote"] = ("Add Note", "إضافة ملاحظة"),
        ["EditNote"] = ("Edit Note", "تعديل الملاحظة"),
        ["DeleteNote"] = ("Delete Note", "حذف الملاحظة"),
        ["AndMore"] = ("and", "و"),
        ["AdditionalNotes"] = ("additional notes", "ملاحظات إضافية"),
        ["AdditionalDocuments"] = ("additional documents", "مستندات إضافية"),

        // Note Properties
        ["NoteType"] = ("Note Type", "نوع الملاحظة"),
        ["NoteSeverity"] = ("Severity", "الخطورة"),
        ["NoteCategory"] = ("Category", "الفئة"),
        ["NoteStatus"] = ("Status", "الحالة"),
        ["NoteContent"] = ("Content", "المحتوى"),
        ["CreatedBy"] = ("Created By", "أنشئت بواسطة"),
        ["CreatedAt"] = ("Created At", "تاريخ الإنشاء"),
        ["ResolvedOn"] = ("Resolved On", "تم الحل في"),
        ["ResolvedBy"] = ("Resolved By", "تم الحل بواسطة"),
        ["ResolutionComment"] = ("Resolution Comment", "تعليق الحل"),

        // Note Types
        ["Observation"] = ("Observation", "ملاحظة"),
        ["Issue"] = ("Issue", "مشكلة"),
        ["Evidence"] = ("Evidence", "دليل"),
        ["Recommendation"] = ("Recommendation", "توصية"),

        // Note Severities
        ["Critical"] = ("Critical", "حرج"),
        ["High"] = ("High", "عالي"),
        ["Medium"] = ("Medium", "متوسط"),

        // Note Status
        ["Open"] = ("Open", "مفتوح"),
        ["Resolved"] = ("Resolved", "محلول"),
        ["Deferred"] = ("Deferred", "مؤجل"),

        // Export options
        ["ExportOptions"] = ("Export Options", "خيارات التصدير"),
        ["IncludeAllNotes"] = ("Include All Notes", "تضمين جميع الملاحظات"),
        ["NoteDetailLevel"] = ("Note Detail Level", "مستوى تفاصيل الملاحظات"),
        ["FullDetail"] = ("Full Detail", "تفاصيل كاملة"),
        ["SummaryOnly"] = ("Summary Only", "ملخص فقط"),
        ["ExcludeNotes"] = ("Exclude Notes", "استبعاد الملاحظات"),

        // KPI Cards
        ["TotalFiles"] = ("Total Files", "إجمالي الملفات"),
        ["CriticalIssues"] = ("Critical Issues", "المشاكل الحرجة"),
        ["ComplianceRate"] = ("Compliance Rate", "معدل الامتثال"),
        ["AvgProcessingTime"] = ("Avg Processing Time", "متوسط وقت المعالجة"),

        ["UnclassifiedDocumentType"] = ("Unclassified", "غير مصنف"),
        ["InputDocumentType"] = ("Document type", "نوع المستند"),
        ["InputSection"] = ("Section", "القسم"),
        ["InputDate"] = ("Date", "التاريخ"),

        // Professional Report Template - Cover Page
        ["CoverPageType"] = ("Type:", "النوع:"),
        ["CoverPageReportId"] = ("Report ID:", "معرف التقرير:"),
        ["CoverPageVersion"] = ("Version:", "الإصدار:"),
        ["CoverPageGeneratedBy"] = ("Generated by:", "أعده:"),
        ["CoverPageGeneratedOn"] = ("on", "في"),
        ["CoverPageConfidential"] = ("CONFIDENTIAL", "سري"),
        ["CoverPageDraft"] = ("DRAFT", "مسودة"),

        // Table of Contents
        ["TableOfContents"] = ("Table of Contents", "جدول المحتويات"),
        ["Page"] = ("Page", "صفحة"),
        ["Section"] = ("Section", "قسم"),

        // Attestation Section
        ["ReportAttestation"] = ("Report Attestation", "توثيق التقرير"),
        ["PreparedBy"] = ("Prepared by:", "أعده:"),
        ["ReviewedBy"] = ("Reviewed by:", "راجعه:"),
        ["ApprovedBy"] = ("Approved by:", "اعتمده:"),
        ["VerificationHash"] = ("Verification Hash:", "توقيع التحقق:"),
        ["StatusGenerated"] = ("GENERATED", "تم الإنشاء"),
        ["StatusReviewed"] = ("REVIEWED", "تمت المراجعة"),
        ["StatusApproved"] = ("APPROVED", "معتمد"),
        ["StatusLabel"] = ("Status:", "الحالة:"),
        ["SignaturePlaceholder"] = ("Signature:", "التوقيع:"),

        // Disclaimers
        ["Disclaimer"] = ("Disclaimer", "إخلاء المسؤولية"),
        ["RegulatoryCompliance"] = ("Regulatory Compliance", "الامتثال التنظيمي"),
        ["ConfidentialityNotice"] = ("Confidentiality Notice", "إشعار السرية"),

        // Comparative Analysis
        ["ComparativeAnalysis"] = ("Comparative Analysis", "التحليل المقارن"),
        ["YearOverYear"] = ("Year-over-Year", "سنة بعد سنة"),
        ["QuarterOverQuarter"] = ("Quarter-over-Quarter", "ربع بعد ربع"),
        ["MonthOverMonth"] = ("Month-over-Month", "شهر بعد شهر"),
        ["PeriodComparison"] = ("Period Comparison", "مقارنة الفترات"),
        ["CurrentPeriod"] = ("Current Period", "الفترة الحالية"),
        ["PreviousPeriod"] = ("Previous Period", "الفترة السابقة"),
        ["Change"] = ("Change", "التغيير"),
        ["PercentChange"] = ("% Change", "% التغيير"),
        ["Trend"] = ("Trend", "الاتجاه"),
        ["Improving"] = ("Improving", "تحسن"),
        ["Declining"] = ("Declining", "تراجع"),
        ["Stable"] = ("Stable", "مستقر"),
        ["NoComparison"] = ("No comparison data", "لا توجد بيانات للمقارنة"),

        // Strategic Insights
        ["StrategicInsights"] = ("Strategic Insights", "الرؤى الاستراتيجية"),
        ["ExecutiveOverview"] = ("Executive Overview", "نظرة تنفيذية عامة"),
        ["KeyFindings"] = ("Key Findings", "النتائج الرئيسية"),
        ["RiskAssessment"] = ("Risk Assessment", "تقييم المخاطر"),
        ["RiskPosture"] = ("Risk Posture", "وضع المخاطر"),
        ["RiskHigh"] = ("High", "عالي"),
        ["RiskModerate"] = ("Moderate", "متوسط"),
        ["RiskLow"] = ("Low", "منخفض"),
        ["StrategicImplications"] = ("Strategic Implications", "التداعيات الاستراتيجية"),
        ["OpportunityAreas"] = ("Opportunity Areas", "مجالات الفرص"),

        // Recommendations
        ["Recommendations"] = ("Recommendations", "التوصيات"),
        ["ActionableRecommendations"] = ("Actionable Recommendations", "التوصيات القابلة للتنفيذ"),
        ["HighPriority"] = ("High Priority", "أولوية عالية"),
        ["MediumPriority"] = ("Medium Priority", "أولوية متوسطة"),
        ["LowPriority"] = ("Low Priority", "أولوية منخفضة"),
        ["CriticalPriority"] = ("Critical", "حرج"),
        ["Impact"] = ("Impact:", "التأثير:"),
        ["EstimatedEffort"] = ("Estimated Effort:", "الجهد المقدر:"),
        ["ResponsibleRole"] = ("Responsible:", "المسؤول:"),
        ["ActionSteps"] = ("Action Steps:", "خطوات الإجراء:"),
        ["Rationale"] = ("Rationale:", "المبرر:"),
        ["ImplementBy"] = ("Implement by:", "التنفيذ بحلول:"),
        ["OneWeek"] = ("1 week", "أسبوع واحد"),
        ["OneMonth"] = ("1 month", "شهر واحد"),
        ["OneQuarter"] = ("1 quarter", "ربع واحد"),

        // Charts and Visualizations
        ["ChartsAndVisualizations"] = ("Charts & Visualizations", "الرسوم البيانية والمرئيات"),
        ["TrendChart"] = ("Trend Chart", "مخطط الاتجاه"),
        ["DistributionChart"] = ("Distribution Chart", "مخطط التوزيع"),
        ["ComparisonChart"] = ("Comparison Chart", "مخطط المقارنة"),
        ["Legend"] = ("Legend", "وسيلة الإيضاح"),
        ["DataPoints"] = ("Data Points", "نقاط البيانات"),

        // Report Sections
        ["BranchAnalysis"] = ("Branch Analysis", "تحليل الفروع"),
        ["SectionAnalysis"] = ("Section Analysis", "تحليل الأقسام"),
        ["IssuesOverview"] = ("Issues Overview", "نظرة عامة على المشكلات"),
        ["PerformanceMetrics"] = ("Performance Metrics", "مقاييس الأداء"),
        ["DocumentDistribution"] = ("Document Distribution", "توزيع المستندات"),
        ["StatusBreakdown"] = ("Status Breakdown", "تفصيل الحالة"),
        ["UserActivitySummary"] = ("User Activity Summary", "ملخص نشاط المستخدم"),
        ["ComplianceStatus"] = ("Compliance Status", "حالة الامتثال"),
        ["AuditTrailSummary"] = ("Audit Trail Summary", "ملخص سجل التدقيق"),

        // Distribution and Version Control
        ["ReportMetadata"] = ("Report Metadata", "بيانات التقرير الوصفية"),
        ["DistributionList"] = ("Distribution List:", "قائمة التوزيع:"),
        ["Supersedes"] = ("Supersedes:", "يحل محل:"),
        ["RetentionPeriod"] = ("Retention Period:", "فترة الاحتفاظ:"),
        ["Years"] = ("years", "سنوات"),
        ["ConfidentialityLevel"] = ("Confidentiality Level:", "مستوى السرية:"),
        ["Public"] = ("Public", "عام"),
        ["Internal"] = ("Internal", "داخلي"),
        ["Restricted"] = ("Restricted", "مقيد"),

        // Footer
        ["PageFooter"] = ("Page {0} of {1}", "صفحة {0} من {1}"),
        ["GeneratedUTC"] = ("Generated {0} UTC", "تم الإنشاء {0} UTC"),
        ["RetainPerPolicy"] = ("Retain per {0}-year policy", "الاحتفاظ لمدة {0} سنوات"),

        // Additional KPIs
        ["AverageProcessingTime"] = ("Average Processing Time", "متوسط وقت المعالجة"),
        ["DocumentsPerDay"] = ("Documents per Day", "المستندات في اليوم"),
        ["ComplianceScore"] = ("Compliance Score", "درجة الامتثال"),
        ["QualityIndex"] = ("Quality Index", "مؤشر الجودة"),
        ["EfficiencyRate"] = ("Efficiency Rate", "معدل الكفاءة"),

        // Time periods
        ["Daily"] = ("Daily", "يومي"),
        ["Weekly"] = ("Weekly", "أسبوعي"),
        ["Monthly"] = ("Monthly", "شهري"),
        ["Quarterly"] = ("Quarterly", "ربع سنوي"),
        ["Yearly"] = ("Yearly", "سنوي"),
        ["ThisMonth"] = ("This Month", "هذا الشهر"),
        ["LastMonth"] = ("Last Month", "الشهر الماضي"),
        ["ThisQuarter"] = ("This Quarter", "هذا الربع"),
        ["LastQuarter"] = ("Last Quarter", "الربع الماضي"),
        ["ThisYear"] = ("This Year", "هذه السنة"),
        ["LastYear"] = ("Last Year", "السنة الماضية"),

        // Report Language Selector
        ["ReportLanguage"] = ("Report Language:", "لغة التقرير:"),
        ["English"] = ("English", "الإنجليزية"),
        ["Arabic"] = ("Arabic (العربية)", "العربية"),
        ["LanguageNote"] = ("Changes text direction and fonts", "يغير اتجاه النص والخطوط"),

        // Diagnostics & Health Monitoring (Control Panel)
        ["DiagnosticsTab"] = ("Diagnostics", "التشخيص"),
        ["DiagnosticsSubOverview"] = ("Overview", "نظرة عامة"),
        ["DiagnosticsSubHealth"] = ("Health Checks", "فحوصات الصحة"),
        ["DiagnosticsSubErrorLog"] = ("Error Log", "سجل الأخطاء"),
        ["DiagnosticsSubWorkflow"] = ("Workflow Issues", "مشكلات سير العمل"),
        ["DiagnosticsSubServices"] = ("Services", "الخدمات"),
        ["DiagnosticsSubDatabase"] = ("Database", "قاعدة البيانات"),
        ["DiagnosticsSubConfiguration"] = ("Configuration", "الإعدادات"),
        ["DiagnosticsSubPerformance"] = ("Performance", "الأداء"),
        ["DiagnosticsRefreshNow"] = ("Refresh Now", "تحديث الآن"),
        ["DiagnosticsRunHealthCheck"] = ("Run Health Check", "تشغيل فحص الصحة"),
        ["DiagnosticsExportReport"] = ("Export Report...", "تصدير التقرير..."),
        ["DiagnosticsAutoRefresh"] = ("Auto-refresh (30s)", "تحديث تلقائي (30ث)"),
        ["DiagnosticsOverallHealth"] = ("Overall Health", "الصحة العامة"),
        ["DiagnosticsErrors24h"] = ("Errors (24h)", "أخطاء (24س)"),
        ["DiagnosticsWarnings24h"] = ("Warnings (24h)", "تحذيرات (24س)"),
        ["DiagnosticsWorkflowIssues"] = ("Workflow Issues", "مشكلات سير العمل"),
        ["DiagnosticsActiveSessions"] = ("Active Sessions", "جلسات نشطة"),
        ["DiagnosticsLastUpdatedUtc"] = ("Last Updated (UTC)", "آخر تحديث (UTC)"),
        ["DiagnosticsSystemOverview"] = ("System Overview", "نظرة عامة على النظام"),
        ["DiagnosticsRecentActivity"] = ("Recent Activity", "النشاط الأخير"),
        ["DiagnosticsTableRowCounts"] = ("Table row counts", "عدد الصفوف في الجداول"),
        ["DiagnosticsClearFilters"] = ("Clear", "مسح"),
        ["DiagnosticsLevel"] = ("Level:", "المستوى:"),
        ["DiagnosticsPeriod"] = ("Period:", "الفترة:"),
        ["DiagnosticsMinDurationMs"] = ("Min duration (ms):", "الحد الأدنى للمدة (مللي ث):"),
        ["DiagnosticsLoading"] = ("Loading diagnostics...", "جاري تحميل التشخيص..."),
        ["DiagnosticsHealthCheckDone"] = ("Health check updated.", "تم تحديث فحص الصحة."),
        ["DiagnosticsExportNoData"] = ("Run Refresh first to collect diagnostics data.", "اضغط تحديث أولاً لجمع بيانات التشخيص."),
        ["DiagnosticsExportSaved"] = ("Report saved.", "تم حفظ التقرير."),
        ["DiagnosticsMetricOverall"] = ("Overall status", "الحالة العامة"),
        ["DiagnosticsMetricDocuments"] = ("Total documents", "إجمالي المستندات"),
        ["DiagnosticsMetricUsers"] = ("Total users", "إجمالي المستخدمين"),
        ["DiagnosticsMetricPendingAssignments"] = ("Pending assignments", "مهام معلقة"),
        ["DiagnosticsMetricOverdueAssignments"] = ("Overdue assignments", "مهام متأخرة"),
        ["DiagnosticsMetricFailedLogins24h"] = ("Failed logins (24h)", "فشل تسجيل الدخول (24س)"),
        ["DiagnosticsActivityLastImport"] = ("Last document import", "آخر استيراد مستند"),
        ["DiagnosticsActivityLastOcr"] = ("Last OCR activity", "آخر نشاط OCR"),
        ["DiagnosticsActivityLastBackup"] = ("Last backup", "آخر نسخ احتياطي"),
        ["DiagnosticsActivityLastReport"] = ("Last generated report", "آخر تقرير مُنشأ"),
        ["DiagnosticsActivityLoginsToday"] = ("Distinct users — login events today", "مستخدمون مميزون — أحداث تسجيل اليوم"),
        ["DiagnosticsErrorTrendTitle"] = ("Error trend (24h, UTC hours)", "اتجاه الأخطاء (24س، ساعات UTC)"),
        ["DiagnosticsColumnMetric"] = ("Metric", "المقياس"),
        ["DiagnosticsColumnValue"] = ("Value", "القيمة"),
        ["DiagnosticsColumnActivity"] = ("Activity", "النشاط"),
        ["DiagnosticsColumnLastOccurrence"] = ("Last occurrence", "آخر حدوث"),
        ["DiagnosticsColumnCountToday"] = ("Count / detail", "العدد / التفاصيل"),
        ["DiagnosticsTrendHourUtc"] = ("Hour (UTC)", "الساعة (UTC)"),
        ["DiagnosticsTrendErrors"] = ("Errors", "أخطاء"),
        ["DiagnosticsTrendWarnings"] = ("Warnings", "تحذيرات"),
        ["DiagnosticsComponentLabel"] = ("Component:", "المكوّن:"),
        ["DiagnosticsComponentAll"] = ("All", "الكل"),
        ["DiagnosticsCopyLogDetails"] = ("Copy details", "نسخ التفاصيل"),
        ["DiagnosticsMetricMissingFiles"] = ("Missing files (workflow sample)", "ملفات مفقودة (عينة من سير العمل)"),
        ["DiagnosticsMetricOrphanFiles"] = ("Orphan files on disk (sample)", "ملفات يتيمة على القرص (عينة)"),
        ["DiagnosticsMetricFailedOcrLogs"] = ("Failed OCR (errors in logs, 7d)", "فشل OCR (أخطاء في السجلات، 7 أيام)"),
        ["DiagnosticsMetricImportErrors24h"] = ("Import-related errors (24h, heuristic)", "أخطاء متعلقة بالاستيراد (24س، تقريبي)"),
        ["DiagnosticsDbConnected"] = ("Connected", "متصل"),
        ["DiagnosticsDbSchemaVersion"] = ("Schema version", "إصدار المخطط"),
        ["DiagnosticsDbProbeMs"] = ("Probe duration (ms)", "مدة الاستكشاف (مللي ث)"),
        ["DiagnosticsDbLogIssues24h"] = ("DB-related log lines (24h)", "أسطر سجل متعلقة بقاعدة البيانات (24س)"),
        ["DiagnosticsDbOracleVSessionTotal"] = ("Oracle v$session (rows)", "Oracle v$session (صفوف)"),
        ["DiagnosticsDbOracleVSessionActive"] = ("Oracle v$session ACTIVE", "Oracle v$session نشطة"),
        ["DiagnosticsCopyDone"] = ("Copied to clipboard.", "تم النسخ إلى الحافظة."),
    };

    /// <summary>Gets localized string for the given key. Uses report_language setting (en/ar).</summary>
    public static string GetString(string key, IConfigStore? configStore = null, params object[] args)
    {
        var lang = configStore?.GetSettingValue(LangKey, "en") ?? "en";
        var isAr = lang.Equals("ar", StringComparison.OrdinalIgnoreCase);
        var template = key;
        if (Strings.TryGetValue(key, out var pair))
            template = isAr ? pair.Ar : pair.En;
        return args.Length > 0 ? string.Format(CultureInfo.CurrentCulture, template, args) : template;
    }

    /// <summary>Returns true if report language is Arabic.</summary>
    public static bool IsArabic(IConfigStore? configStore)
    {
        var lang = configStore?.GetSettingValue(LangKey, "en") ?? "en";
        return lang.Equals("ar", StringComparison.OrdinalIgnoreCase);
    }

    /// <summary>Label for lists/grids: unclassified when null/empty or legacy Other; otherwise the stored type.</summary>
    public static string GetDocumentTypeListLabel(string? documentType, IConfigStore? configStore = null)
    {
        if (DocumentTypeInfo.IsUnclassified(documentType))
            return GetString("UnclassifiedDocumentType", configStore);
        return documentType!.Trim();
    }
}
