using Oracle.ManagedDataAccess.Client;
using Serilog;
using WorkAudit.Core.Services;

namespace WorkAudit.Storage.Oracle;

/// <summary>Creates Oracle baseline schema at version 49 for fresh installs.</summary>
internal static class OracleBaselineInstaller
{
    private static readonly ILogger Log = LoggingService.ForContext(typeof(OracleBaselineInstaller));

    public const int BaselineVersion = 49;

    public static void Install(OracleConnection conn)
    {
        foreach (var batch in GetTableStatements())
            ExecuteIgnoringExists(conn, batch);

        foreach (var ix in GetIndexStatements())
            ExecuteIgnoringExists(conn, ix);

        TryCreateContextIndexes(conn);
        SeedDefaults(conn);
    }

    private static void ExecuteIgnoringExists(OracleConnection conn, string sql)
    {
        try
        {
            using var cmd = OracleSql.CreateCommand(conn, sql);
            cmd.ExecuteNonQuery();
        }
        catch (OracleException ex) when (ex.Number is 955 or 1408 or 1430 or 2264 or 2261 or 2275 or 942)
        {
            Log.Debug(ex, "Skipped DDL (already applied): {Sql}", sql.Length > 120 ? sql[..120] + "..." : sql);
        }
    }

    private static IEnumerable<string> GetTableStatements()
    {
        yield return """
            CREATE TABLE workaudit_migrations (
              version NUMBER(10,0) PRIMARY KEY,
              name VARCHAR2(512) NOT NULL,
              applied_at VARCHAR2(64) NOT NULL
            )
            """;

        yield return """
            CREATE TABLE users (
              id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              uuid VARCHAR2(64) NOT NULL,
              username VARCHAR2(256) NOT NULL,
              display_name VARCHAR2(512) NOT NULL,
              email VARCHAR2(512),
              password_hash VARCHAR2(512) NOT NULL,
              role VARCHAR2(64) DEFAULT 'Auditor' NOT NULL,
              branch VARCHAR2(128),
              department VARCHAR2(256),
              is_active NUMBER(1,0) DEFAULT 1,
              is_locked NUMBER(1,0) DEFAULT 0,
              failed_login_attempts NUMBER(10,0) DEFAULT 0,
              last_login_at VARCHAR2(64),
              last_login_ip VARCHAR2(128),
              password_changed_at VARCHAR2(64),
              created_at VARCHAR2(64) NOT NULL,
              created_by VARCHAR2(256),
              updated_at VARCHAR2(64),
              updated_by VARCHAR2(256),
              must_change_password NUMBER(1,0) DEFAULT 0 NOT NULL,
              CONSTRAINT uq_users_uuid UNIQUE (uuid),
              CONSTRAINT uq_users_username UNIQUE (username)
            )
            """;

        yield return """
            CREATE TABLE documents (
              id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              uuid VARCHAR2(64),
              file_path VARCHAR2(4000) NOT NULL,
              document_type VARCHAR2(512),
              extracted_date VARCHAR2(64),
              amounts VARCHAR2(4000),
              snippet CLOB,
              ocr_text CLOB,
              capture_time VARCHAR2(64) NOT NULL,
              source VARCHAR2(512) NOT NULL,
              engagement VARCHAR2(512) NOT NULL,
              section VARCHAR2(128) NOT NULL,
              clearing_direction VARCHAR2(128),
              clearing_status VARCHAR2(128),
              notes CLOB,
              confidence BINARY_FLOAT,
              status VARCHAR2(64) DEFAULT 'Draft' NOT NULL,
              reviewed_at VARCHAR2(64),
              updated_at VARCHAR2(64),
              branch VARCHAR2(128),
              explanation CLOB,
              created_by VARCHAR2(256),
              reviewed_by VARCHAR2(256),
              category VARCHAR2(256),
              file_hash VARCHAR2(128),
              file_size NUMBER(19,0),
              page_count NUMBER(10,0) DEFAULT 1,
              ocr_language VARCHAR2(64),
              ocr_duration_ms NUMBER(10,0),
              classification_confidence BINARY_FLOAT,
              is_duplicate NUMBER(1,0) DEFAULT 0,
              duplicate_of VARCHAR2(64),
              tags VARCHAR2(4000),
              custom_fields CLOB,
              archived_at VARCHAR2(64),
              archived_by NUMBER(10,0),
              legal_hold NUMBER(1,0) DEFAULT 0,
              legal_hold_reason VARCHAR2(4000),
              legal_hold_case_number VARCHAR2(512),
              legal_hold_applied_at VARCHAR2(64),
              legal_hold_applied_by NUMBER(10,0),
              retention_expiry_date VARCHAR2(64),
              is_immutable NUMBER(1,0) DEFAULT 0,
              immutable_hash VARCHAR2(128),
              immutable_since VARCHAR2(64),
              hash_verification_count NUMBER(10,0) DEFAULT 0,
              last_hash_verification VARCHAR2(64),
              custodian_id NUMBER(10,0),
              disposal_status VARCHAR2(64),
              disposal_requested_at VARCHAR2(64),
              disposal_requested_by NUMBER(10,0),
              disposal_approved_at VARCHAR2(64),
              disposal_approved_by NUMBER(10,0),
              disposal_rejected_at VARCHAR2(64),
              disposal_rejected_by NUMBER(10,0),
              disposal_rejection_reason VARCHAR2(4000),
              account_name VARCHAR2(512),
              account_number VARCHAR2(512),
              transaction_reference VARCHAR2(512),
              CONSTRAINT uq_documents_uuid UNIQUE (uuid)
            )
            """;

        yield return """
            CREATE TABLE sessions (
              id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              token VARCHAR2(512) NOT NULL,
              user_id NUMBER(10,0) NOT NULL,
              username VARCHAR2(256) NOT NULL,
              user_role VARCHAR2(64) NOT NULL,
              created_at VARCHAR2(64) NOT NULL,
              expires_at VARCHAR2(64) NOT NULL,
              ip_address VARCHAR2(128),
              user_agent VARCHAR2(4000),
              is_active NUMBER(1,0) DEFAULT 1,
              CONSTRAINT uq_sessions_token UNIQUE (token),
              CONSTRAINT fk_sessions_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
            )
            """;

        yield return """
            CREATE TABLE audit_log (
              id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              uuid VARCHAR2(64) NOT NULL,
              timestamp VARCHAR2(64) NOT NULL,
              user_id VARCHAR2(64) NOT NULL,
              username VARCHAR2(256) NOT NULL,
              user_role VARCHAR2(64) NOT NULL,
              action VARCHAR2(256) NOT NULL,
              category VARCHAR2(128) NOT NULL,
              entity_type VARCHAR2(128) NOT NULL,
              entity_id VARCHAR2(256),
              entity_name VARCHAR2(512),
              old_value CLOB,
              new_value CLOB,
              ip_address VARCHAR2(128),
              details CLOB,
              success NUMBER(1,0) DEFAULT 1,
              error_message VARCHAR2(4000),
              CONSTRAINT uq_audit_log_uuid UNIQUE (uuid)
            )
            """;

        yield return """
            CREATE TABLE classification_feedback (
              id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              document_uuid VARCHAR2(64) NOT NULL,
              correct_type VARCHAR2(512) NOT NULL,
              ocr_text CLOB,
              created_at VARCHAR2(64) NOT NULL
            )
            """;

        yield return """
            CREATE TABLE document_change_history (
              id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              document_uuid VARCHAR2(64) NOT NULL,
              document_id NUMBER(10,0) NOT NULL,
              field_name VARCHAR2(256) NOT NULL,
              old_value CLOB,
              new_value CLOB,
              changed_at VARCHAR2(64) NOT NULL,
              changed_by VARCHAR2(256)
            )
            """;

        yield return """
            CREATE TABLE config_document_types (
              id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              name VARCHAR2(512) NOT NULL,
              category VARCHAR2(128) NOT NULL,
              keywords VARCHAR2(4000),
              is_active NUMBER(1,0) DEFAULT 1,
              display_order NUMBER(10,0) DEFAULT 0,
              created_at VARCHAR2(64) NOT NULL,
              updated_at VARCHAR2(64),
              branch VARCHAR2(128),
              section VARCHAR2(128),
              CONSTRAINT uq_config_doc_types_name UNIQUE (name)
            )
            """;

        yield return """
            CREATE TABLE config_branches (
              id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              name VARCHAR2(256) NOT NULL,
              code VARCHAR2(64),
              is_active NUMBER(1,0) DEFAULT 1,
              display_order NUMBER(10,0) DEFAULT 0,
              created_at VARCHAR2(64) NOT NULL,
              updated_at VARCHAR2(64),
              CONSTRAINT uq_config_branches_name UNIQUE (name)
            )
            """;

        yield return """
            CREATE TABLE config_categories (
              id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              name VARCHAR2(128) NOT NULL,
              description VARCHAR2(4000),
              is_active NUMBER(1,0) DEFAULT 1,
              display_order NUMBER(10,0) DEFAULT 0,
              created_at VARCHAR2(64) NOT NULL,
              updated_at VARCHAR2(64),
              CONSTRAINT uq_config_categories_name UNIQUE (name)
            )
            """;

        yield return """
            CREATE TABLE app_settings (
              key VARCHAR2(512) PRIMARY KEY NOT NULL,
              value CLOB,
              category VARCHAR2(128) NOT NULL,
              description VARCHAR2(4000),
              value_type VARCHAR2(64) DEFAULT 'string',
              updated_at VARCHAR2(64),
              updated_by VARCHAR2(256)
            )
            """;

        yield return """
            CREATE TABLE notifications (
              id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              user_id NUMBER(10,0) NOT NULL,
              type VARCHAR2(128) NOT NULL,
              title VARCHAR2(512) NOT NULL,
              message CLOB,
              entity_type VARCHAR2(128),
              entity_id NUMBER(10,0),
              is_read NUMBER(1,0) DEFAULT 0,
              created_at VARCHAR2(64) NOT NULL,
              read_at VARCHAR2(64),
              priority VARCHAR2(64) DEFAULT 'Normal' NOT NULL
            )
            """;

        yield return """
            CREATE TABLE document_assignments (
              id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              uuid VARCHAR2(64) NOT NULL,
              document_id NUMBER(10,0) NOT NULL,
              document_uuid VARCHAR2(64) NOT NULL,
              assigned_to_user_id NUMBER(10,0) NOT NULL,
              assigned_to_username VARCHAR2(256) NOT NULL,
              assigned_by_user_id NUMBER(10,0) NOT NULL,
              assigned_by_username VARCHAR2(256) NOT NULL,
              assigned_at VARCHAR2(64) NOT NULL,
              due_date VARCHAR2(64),
              priority VARCHAR2(64) DEFAULT 'Normal' NOT NULL,
              status VARCHAR2(64) DEFAULT 'Pending' NOT NULL,
              notes CLOB,
              started_at VARCHAR2(64),
              completed_at VARCHAR2(64),
              completion_notes CLOB,
              CONSTRAINT uq_doc_assign_uuid UNIQUE (uuid),
              CONSTRAINT fk_doc_assign_doc FOREIGN KEY (document_id) REFERENCES documents (id),
              CONSTRAINT fk_doc_assign_to_user FOREIGN KEY (assigned_to_user_id) REFERENCES users (id),
              CONSTRAINT fk_doc_assign_by_user FOREIGN KEY (assigned_by_user_id) REFERENCES users (id)
            )
            """;

        yield return """
            CREATE TABLE report_attestations (
              id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              uuid VARCHAR2(64) NOT NULL,
              report_type VARCHAR2(128) NOT NULL,
              report_path VARCHAR2(4000) NOT NULL,
              date_from VARCHAR2(64) NOT NULL,
              date_to VARCHAR2(64) NOT NULL,
              branch VARCHAR2(128),
              section VARCHAR2(128),
              sha256_hash VARCHAR2(128) NOT NULL,
              status VARCHAR2(64) DEFAULT 'Generated' NOT NULL,
              generated_at VARCHAR2(64) NOT NULL,
              generated_by_user_id VARCHAR2(64),
              generated_by_username VARCHAR2(256),
              reviewed_at VARCHAR2(64),
              reviewed_by_user_id VARCHAR2(64),
              reviewed_by_username VARCHAR2(256),
              approved_at VARCHAR2(64),
              approved_by_user_id VARCHAR2(64),
              approved_by_username VARCHAR2(256),
              notes CLOB,
              CONSTRAINT uq_report_attest_uuid UNIQUE (uuid)
            )
            """;

        yield return """
            CREATE TABLE report_distributions (
              id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              uuid VARCHAR2(64) NOT NULL,
              report_path VARCHAR2(4000) NOT NULL,
              report_type VARCHAR2(128) NOT NULL,
              event_type VARCHAR2(128) NOT NULL,
              user_id VARCHAR2(64) NOT NULL,
              username VARCHAR2(256) NOT NULL,
              timestamp VARCHAR2(64) NOT NULL,
              details CLOB,
              CONSTRAINT uq_report_dist_uuid UNIQUE (uuid)
            )
            """;

        yield return """
            CREATE TABLE report_history (
              id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              uuid VARCHAR2(64) NOT NULL,
              user_id VARCHAR2(64) NOT NULL,
              username VARCHAR2(256) NOT NULL,
              report_type VARCHAR2(128) NOT NULL,
              file_path VARCHAR2(4000) NOT NULL,
              generated_at TIMESTAMP(6) NOT NULL,
              config_json CLOB,
              tags VARCHAR2(4000),
              purpose VARCHAR2(512),
              description VARCHAR2(4000),
              version NUMBER(10,0),
              parent_report_id VARCHAR2(64),
              app_version VARCHAR2(64),
              CONSTRAINT uq_report_hist_uuid UNIQUE (uuid)
            )
            """;

        yield return """
            CREATE TABLE notes (
              id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              uuid VARCHAR2(64) NOT NULL,
              document_id NUMBER(10,0) NOT NULL,
              document_uuid VARCHAR2(64) NOT NULL,
              content CLOB NOT NULL,
              type VARCHAR2(64) DEFAULT 'Observation' NOT NULL,
              severity VARCHAR2(64) DEFAULT 'Info' NOT NULL,
              category VARCHAR2(256),
              created_at VARCHAR2(64) NOT NULL,
              created_by VARCHAR2(256) NOT NULL,
              created_by_user_id NUMBER(10,0),
              updated_at VARCHAR2(64),
              updated_by VARCHAR2(256),
              status VARCHAR2(64) DEFAULT 'Open' NOT NULL,
              resolved_at VARCHAR2(64),
              resolved_by VARCHAR2(256),
              resolution_comment CLOB,
              attachments CLOB,
              tags VARCHAR2(4000),
              CONSTRAINT uq_notes_uuid UNIQUE (uuid),
              CONSTRAINT fk_notes_document FOREIGN KEY (document_id) REFERENCES documents (id) ON DELETE CASCADE
            )
            """;

        yield return """
            CREATE TABLE report_drafts (
              id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              uuid VARCHAR2(64) NOT NULL,
              user_id VARCHAR2(64) NOT NULL,
              username VARCHAR2(256) NOT NULL,
              report_type VARCHAR2(128) NOT NULL,
              created_at VARCHAR2(64) NOT NULL,
              last_modified_at VARCHAR2(64),
              config_json CLOB NOT NULL,
              draft_file_path VARCHAR2(4000) NOT NULL,
              title VARCHAR2(512),
              notes CLOB,
              tags VARCHAR2(4000),
              is_finalized NUMBER(1,0) DEFAULT 0 NOT NULL,
              exported_report_history_id VARCHAR2(64),
              CONSTRAINT uq_report_drafts_uuid UNIQUE (uuid)
            )
            """;

        yield return """
            CREATE TABLE report_templates (
              id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              name VARCHAR2(512) NOT NULL,
              description VARCHAR2(4000),
              report_type VARCHAR2(128) NOT NULL,
              created_by NUMBER(10,0) NOT NULL,
              created_at VARCHAR2(64) NOT NULL,
              updated_at VARCHAR2(64),
              is_shared NUMBER(1,0) DEFAULT 0 NOT NULL,
              fields_json CLOB NOT NULL,
              filters_json CLOB,
              sorting_json CLOB,
              grouping_json CLOB,
              CONSTRAINT fk_report_tpl_user FOREIGN KEY (created_by) REFERENCES users (id)
            )
            """;

        yield return """
            CREATE TABLE document_markup_regions (
              id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              document_id NUMBER(10,0) NOT NULL,
              kind VARCHAR2(64) NOT NULL,
              color VARCHAR2(64) NOT NULL,
              norm_x BINARY_FLOAT NOT NULL,
              norm_y BINARY_FLOAT NOT NULL,
              norm_w BINARY_FLOAT NOT NULL,
              norm_h BINARY_FLOAT NOT NULL,
              page_index NUMBER(10,0) DEFAULT 0 NOT NULL,
              preview_surface VARCHAR2(64) DEFAULT 'Image' NOT NULL,
              note_id NUMBER(10,0),
              label VARCHAR2(512),
              created_at VARCHAR2(64) NOT NULL,
              created_by VARCHAR2(256) NOT NULL,
              CONSTRAINT fk_markup_document FOREIGN KEY (document_id) REFERENCES documents (id) ON DELETE CASCADE
            )
            """;

        yield return """
            CREATE TABLE team_tasks (
              id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              uuid VARCHAR2(64) NOT NULL,
              title VARCHAR2(512) NOT NULL,
              description CLOB,
              assigned_to_user_id NUMBER(10,0) NOT NULL,
              assigned_to_username VARCHAR2(256) NOT NULL,
              assigned_by_user_id NUMBER(10,0) NOT NULL,
              assigned_by_username VARCHAR2(256) NOT NULL,
              recurrence VARCHAR2(128) NOT NULL,
              start_date VARCHAR2(64) NOT NULL,
              end_date VARCHAR2(64),
              is_active NUMBER(1,0) DEFAULT 1 NOT NULL,
              created_at VARCHAR2(64) NOT NULL,
              updated_at VARCHAR2(64) NOT NULL,
              CONSTRAINT uq_team_tasks_uuid UNIQUE (uuid),
              CONSTRAINT fk_team_tasks_assignee FOREIGN KEY (assigned_to_user_id) REFERENCES users (id),
              CONSTRAINT fk_team_tasks_assigner FOREIGN KEY (assigned_by_user_id) REFERENCES users (id)
            )
            """;

        yield return """
            CREATE TABLE team_task_completions (
              id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              team_task_id NUMBER(10,0) NOT NULL,
              period_key VARCHAR2(64) NOT NULL,
              completed_at VARCHAR2(64) NOT NULL,
              CONSTRAINT uq_team_task_completion UNIQUE (team_task_id, period_key),
              CONSTRAINT fk_team_task_completion_task FOREIGN KEY (team_task_id) REFERENCES team_tasks (id)
            )
            """;

        yield return """
            CREATE TABLE team_task_notes (
              id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              team_task_id NUMBER(10,0) NOT NULL,
              user_id NUMBER(10,0) NOT NULL,
              period_key VARCHAR2(64) NOT NULL,
              note_text CLOB NOT NULL,
              updated_at VARCHAR2(64) NOT NULL,
              CONSTRAINT uq_team_task_notes UNIQUE (team_task_id, user_id, period_key),
              CONSTRAINT fk_team_task_notes_task FOREIGN KEY (team_task_id) REFERENCES team_tasks (id),
              CONSTRAINT fk_team_task_notes_user FOREIGN KEY (user_id) REFERENCES users (id)
            )
            """;

        yield return """
            CREATE TABLE user_emergency_codes (
              id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              user_id NUMBER(10,0) NOT NULL,
              code_hash VARCHAR2(512) NOT NULL,
              created_at VARCHAR2(64) NOT NULL,
              used_at VARCHAR2(64),
              CONSTRAINT fk_emergency_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
            )
            """;
    }

    private static IEnumerable<string> GetIndexStatements()
    {
        string[] ix =
        [
            """CREATE INDEX idx_documents_section ON documents (section)""",
            """CREATE INDEX idx_documents_capture_time ON documents (capture_time)""",
            """CREATE INDEX idx_documents_engagement ON documents (engagement)""",
            """CREATE INDEX idx_documents_uuid ON documents (uuid)""",
            """CREATE INDEX idx_documents_status ON documents (status)""",
            """CREATE INDEX idx_documents_document_type ON documents (document_type)""",
            """CREATE INDEX idx_documents_file_hash ON documents (file_hash)""",
            """CREATE INDEX idx_documents_status_archived_at ON documents (status, archived_at)""",
            """CREATE INDEX idx_documents_archived_at ON documents (archived_at)""",
            """CREATE INDEX idx_documents_retention_expiry ON documents (retention_expiry_date)""",
            """CREATE INDEX idx_documents_archived_by ON documents (archived_by)""",
            """CREATE INDEX idx_documents_legal_hold_applied_by ON documents (legal_hold_applied_by)""",
            """CREATE INDEX idx_documents_custodian_id ON documents (custodian_id)""",
            """CREATE INDEX idx_documents_created_by ON documents (created_by)""",
            """CREATE INDEX idx_documents_reviewed_by ON documents (reviewed_by)""",
            """CREATE INDEX idx_documents_extracted_date ON documents (extracted_date)""",
            """CREATE INDEX idx_documents_disposal_status ON documents (disposal_status)""",
            """CREATE INDEX idx_audit_timestamp ON audit_log (timestamp)""",
            """CREATE INDEX idx_audit_user_id ON audit_log (user_id)""",
            """CREATE INDEX idx_audit_action ON audit_log (action)""",
            """CREATE INDEX idx_audit_category ON audit_log (category)""",
            """CREATE INDEX idx_audit_entity ON audit_log (entity_type, entity_id)""",
            """CREATE INDEX idx_audit_log_entity_id ON audit_log (entity_id)""",
            """CREATE INDEX idx_audit_log_action_timestamp ON audit_log (action, timestamp)""",
            """CREATE INDEX idx_users_username ON users (username)""",
            """CREATE INDEX idx_users_uuid ON users (uuid)""",
            """CREATE INDEX idx_users_role ON users (role)""",
            """CREATE INDEX idx_sessions_token ON sessions (token)""",
            """CREATE INDEX idx_sessions_user_id ON sessions (user_id)""",
            """CREATE INDEX idx_classification_feedback_document_uuid ON classification_feedback (document_uuid)""",
            """CREATE INDEX idx_doc_history_document_uuid ON document_change_history (document_uuid)""",
            """CREATE INDEX idx_doc_history_changed_at ON document_change_history (changed_at)""",
            """CREATE INDEX idx_config_doc_types_category ON config_document_types (category)""",
            """CREATE INDEX idx_config_doc_types_active ON config_document_types (is_active)""",
            """CREATE INDEX idx_config_branches_active ON config_branches (is_active)""",
            """CREATE INDEX idx_app_settings_category ON app_settings (category)""",
            """CREATE INDEX idx_notifications_user_unread ON notifications (user_id, is_read)""",
            """CREATE INDEX idx_assignments_user ON document_assignments (assigned_to_user_id, status)""",
            """CREATE INDEX idx_assignments_status ON document_assignments (status)""",
            """CREATE INDEX idx_assignments_due_date ON document_assignments (due_date)""",
            """CREATE INDEX idx_assignments_document ON document_assignments (document_id)""",
            """CREATE INDEX idx_report_attestations_path ON report_attestations (report_path)""",
            """CREATE INDEX idx_report_attestations_type ON report_attestations (report_type)""",
            """CREATE INDEX idx_report_attestations_status ON report_attestations (status)""",
            """CREATE INDEX idx_report_attestations_generated ON report_attestations (generated_at)""",
            """CREATE INDEX idx_report_dist_path ON report_distributions (report_path)""",
            """CREATE INDEX idx_report_dist_user ON report_distributions (user_id)""",
            """CREATE INDEX idx_report_dist_timestamp ON report_distributions (timestamp)""",
            """CREATE INDEX idx_report_history_user ON report_history (user_id)""",
            """CREATE INDEX idx_report_history_date ON report_history (generated_at)""",
            """CREATE INDEX idx_report_history_tags ON report_history (tags)""",
            """CREATE INDEX idx_notes_document_id ON notes (document_id)""",
            """CREATE INDEX idx_notes_document_uuid ON notes (document_uuid)""",
            """CREATE INDEX idx_notes_type ON notes (type)""",
            """CREATE INDEX idx_notes_severity ON notes (severity)""",
            """CREATE INDEX idx_notes_status ON notes (status)""",
            """CREATE INDEX idx_notes_created_by ON notes (created_by_user_id)""",
            """CREATE INDEX idx_notes_created_at ON notes (created_at)""",
            """CREATE INDEX idx_report_drafts_user_id ON report_drafts (user_id)""",
            """CREATE INDEX idx_report_drafts_created_at ON report_drafts (created_at)""",
            """CREATE INDEX idx_report_drafts_finalized ON report_drafts (is_finalized)""",
            """CREATE INDEX idx_report_templates_created_by ON report_templates (created_by)""",
            """CREATE INDEX idx_report_templates_type ON report_templates (report_type)""",
            """CREATE INDEX idx_report_templates_shared ON report_templates (is_shared)""",
            """CREATE INDEX idx_markup_document ON document_markup_regions (document_id)""",
            """CREATE INDEX idx_team_tasks_assignee ON team_tasks (assigned_to_user_id, is_active)""",
            """CREATE INDEX idx_team_tasks_active ON team_tasks (is_active)""",
            """CREATE INDEX idx_team_task_completions_task ON team_task_completions (team_task_id)""",
            """CREATE INDEX idx_team_task_notes_lookup ON team_task_notes (team_task_id, user_id, period_key)""",
            """CREATE INDEX idx_user_emergency_codes_user_used ON user_emergency_codes (user_id, used_at)"""
        ];
        foreach (var s in ix) yield return s;
    }

    private static void TryCreateContextIndexes(OracleConnection conn)
    {
        string[] stmts =
        [
            """CREATE INDEX idx_ctx_documents_ocr ON documents (ocr_text) INDEXTYPE IS CTXSYS.CONTEXT""",
            """CREATE INDEX idx_ctx_documents_snippet ON documents (snippet) INDEXTYPE IS CTXSYS.CONTEXT""",
            """CREATE INDEX idx_ctx_documents_notes ON documents (notes) INDEXTYPE IS CTXSYS.CONTEXT"""
        ];
        foreach (var sql in stmts)
        {
            try
            {
                using var cmd = OracleSql.CreateCommand(conn, sql);
                cmd.ExecuteNonQuery();
            }
            catch (OracleException ex)
            {
                Log.Warning(ex, "Oracle Text index not created (missing privileges or lexer); full-text search may use LIKE fallback");
                break;
            }
        }

        try
        {
            using var cmd = OracleSql.CreateCommand(conn,
                """CREATE INDEX idx_ctx_documents_doctype ON documents (document_type) INDEXTYPE IS CTXSYS.CONTEXT""");
            cmd.ExecuteNonQuery();
        }
        catch (OracleException ex)
        {
            Log.Warning(ex, "Oracle Text index on document_type skipped");
        }
    }

    private static void SeedDefaults(OracleConnection conn)
    {
        OracleSeedData.Apply(conn);
    }
}
